# Generated by Django 2.1.5 on 2019-02-15 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='responder',
            new_name='user',
        ),
    ]
